In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
data = load_breast_cancer()

X = data.data
y = data.target

df = pd.DataFrame(X, columns=data.feature_names)
df['target'] = y

print("Dataset Shape:", df.shape)
print("\nFirst 5 rows:\n", df.head())

Dataset Shape: (569, 31)

First 5 rows:
    mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  wors

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [4]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
base_model = DecisionTreeClassifier(random_state=42)

base_model.fit(X_train, y_train)
base_pred = base_model.predict(X_test)

print("\n===== Base Model (Decision Tree) =====")
print("Accuracy:", accuracy_score(y_test, base_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, base_pred))
print("Classification Report:\n", classification_report(y_test, base_pred))


===== Base Model (Decision Tree) =====
Accuracy: 0.9122807017543859
Confusion Matrix:
 [[39  3]
 [ 7 65]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.93      0.89        42
           1       0.96      0.90      0.93        72

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114



In [6]:
bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=50,
    random_state=42
)

bagging_model.fit(X_train, y_train)
bagging_pred = bagging_model.predict(X_test)

print("\n===== Bagging Classifier =====")
print("Accuracy:", accuracy_score(y_test, bagging_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, bagging_pred))
print("Classification Report:\n", classification_report(y_test, bagging_pred))


===== Bagging Classifier =====
Accuracy: 0.9385964912280702
Confusion Matrix:
 [[38  4]
 [ 3 69]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.90      0.92        42
           1       0.95      0.96      0.95        72

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114



In [7]:
adaboost_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=50,
    learning_rate=1.0,
    random_state=42
)

adaboost_model.fit(X_train, y_train)
adaboost_pred = adaboost_model.predict(X_test)

print("\n===== AdaBoost Classifier =====")
print("Accuracy:", accuracy_score(y_test, adaboost_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, adaboost_pred))
print("Classification Report:\n", classification_report(y_test, adaboost_pred))


===== AdaBoost Classifier =====
Accuracy: 0.956140350877193
Confusion Matrix:
 [[38  4]
 [ 1 71]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [8]:
gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)
gb_pred = gb_model.predict(X_test)

print("\n===== Gradient Boosting Classifier =====")
print("Accuracy:", accuracy_score(y_test, gb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, gb_pred))
print("Classification Report:\n", classification_report(y_test, gb_pred))


===== Gradient Boosting Classifier =====
Accuracy: 0.956140350877193
Confusion Matrix:
 [[38  4]
 [ 1 71]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [9]:
results = pd.DataFrame({
    'Model': [
        'Decision Tree',
        'Bagging',
        'AdaBoost',
        'Gradient Boosting'
    ],
    'Accuracy': [
        accuracy_score(y_test, base_pred),
        accuracy_score(y_test, bagging_pred),
        accuracy_score(y_test, adaboost_pred),
        accuracy_score(y_test, gb_pred)
    ]
})

print("\n===== Model Comparison =====")
print(results)


===== Model Comparison =====
               Model  Accuracy
0      Decision Tree  0.912281
1            Bagging  0.938596
2           AdaBoost  0.956140
3  Gradient Boosting  0.956140


In [10]:
results.to_csv("bagging_boosting_results.csv", index=False)